/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import DAO.AlunoDAO;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.Connect;
import utils.LeituraEscritaObj;

/**
 *
 * @author wesle
 */
public class FrmAlunoBuscar extends javax.swing.JFrame {

    public Connect con = new Connect();
    LeituraEscritaObj ler = new LeituraEscritaObj();

    /**
     * Creates new form FrmAlunoBuscar
     */
    public FrmAlunoBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAluno = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idUsuario", "nome", "CPF", "RG", "telefone", "celular", "email", "nivelAcesso", "Acesso_usuario", "matriculaAluno", "dataMatricula", "profissao", "status"
            }
        ));
        jScrollPane1.setViewportView(jTableAluno);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Buscar Aluno");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Buscar Aluno:");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(594, 594, 594))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(546, 546, 546))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        try {
            // TODO add your handling code here:
            con = ler.restaurar();
        } catch (IOException ex) {
            Logger.getLogger(FrmAlunoBuscar.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTableAluno.setModel(modelo);     //é o nome da minha jTable
            
            modelo.addColumn("idUsuario");
            modelo.addColumn("Nome");
            modelo.addColumn("CPF");
            modelo.addColumn("RG");
            modelo.addColumn("Telefone");
            modelo.addColumn("Celular");
            modelo.addColumn("E-mail");
            modelo.addColumn("Nivel de Acesso");
            modelo.addColumn("Login");
            modelo.addColumn("Matricula Aluno");
            modelo.addColumn("Data Matricula");
            modelo.addColumn("profissao");
            modelo.addColumn("status");
            
            jTableAluno.getColumnModel().getColumn(0).setPreferredWidth(0);   //Tamanho da Coluna 1
            jTableAluno.getColumnModel().getColumn(1).setPreferredWidth(40);    //Tamnaho da Coluna 2
            jTableAluno.getColumnModel().getColumn(2).setPreferredWidth(20);   //Tamanho da Coluna 3
            
            jTableAluno.getColumnModel().getColumn(3).setPreferredWidth(20);   //Tamanho da Coluna 1
            jTableAluno.getColumnModel().getColumn(4).setPreferredWidth(20);    //Tamnaho da Coluna 2
            jTableAluno.getColumnModel().getColumn(5).setPreferredWidth(20);   //Tamanho da Coluna 3
            
            jTableAluno.getColumnModel().getColumn(6).setPreferredWidth(20);   //Tamanho da Coluna 1
            jTableAluno.getColumnModel().getColumn(7).setPreferredWidth(20);    //Tamnaho da Coluna 2
            jTableAluno.getColumnModel().getColumn(8).setPreferredWidth(0);   //Tamanho da Coluna 3
            
            jTableAluno.getColumnModel().getColumn(9).setPreferredWidth(20);   //Tamanho da Coluna 1
            jTableAluno.getColumnModel().getColumn(10).setPreferredWidth(20);    //Tamnaho da Coluna 2
            jTableAluno.getColumnModel().getColumn(11).setPreferredWidth(20);   //Tamanho da Coluna 3

            //Pesquisa todos os Estados Cadastrados no banco de dados.
            AlunoDAO aluno = new AlunoDAO();
            ResultSet rs = aluno.buscaTodosAluno(con);

            //Apresenta todos os estados cadastrado no grid
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("idUsuario"),
                    rs.getString("nome"),
                    rs.getString("CPF"),
                    rs.getString("RG"),
                    rs.getString("telefone"),
                    rs.getString("celular"),
                    rs.getString("email"),
                    rs.getString("nivelAcesso"),
                    rs.getString("Acesso_usuario"),
                    rs.getString("matriculaAluno"),
                    rs.getString("dataMatricula"),
                    rs.getString("profissao"),
                    rs.getString("status")});
            }
        } catch (Exception e) {
            System.out.println("Problemas com a carga do Grid ");
        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlunoBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlunoBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlunoBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlunoBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlunoBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAluno;
    // End of variables declaration//GEN-END:variables
}
