/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author wesle
 */
public class FrmPrincipalAdm extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipalAdm
     */
    public FrmPrincipalAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastroAluno = new javax.swing.JMenu();
        jAlunoItemCadastrarAlterarDeletar = new javax.swing.JMenuItem();
        jFuncionario = new javax.swing.JMenu();
        jFuncionarioItemCadastrarAlterarDeletar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jFaturaItemEmitir = new javax.swing.JMenuItem();
        jFaturaItemBaixaFatura = new javax.swing.JMenuItem();
        jTreinos = new javax.swing.JMenu();
        jTreinosItemCadastrar = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jExercicios = new javax.swing.JMenu();
        jExercicioItemCadastrar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jGerenciarNivelAcesso = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jConfigBD = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        Jsair = new javax.swing.JMenu();
        jSairItemLogout = new javax.swing.JMenuItem();
        jSairItemSairSistema = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homem1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCadastroAluno.setText("Aluno");

        jAlunoItemCadastrarAlterarDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquivo.jpg"))); // NOI18N
        jAlunoItemCadastrarAlterarDeletar.setText("Cadastrar/Alterar/Deletar");
        jAlunoItemCadastrarAlterarDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlunoItemCadastrarAlterarDeletarActionPerformed(evt);
            }
        });
        jCadastroAluno.add(jAlunoItemCadastrarAlterarDeletar);

        jMenuBar1.add(jCadastroAluno);

        jFuncionario.setText("Funcionário");

        jFuncionarioItemCadastrarAlterarDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquivo.jpg"))); // NOI18N
        jFuncionarioItemCadastrarAlterarDeletar.setText("Cadastrar/Alterar/Deletar");
        jFuncionarioItemCadastrarAlterarDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFuncionarioItemCadastrarAlterarDeletarActionPerformed(evt);
            }
        });
        jFuncionario.add(jFuncionarioItemCadastrarAlterarDeletar);
        jFuncionario.add(jSeparator2);

        jMenuBar1.add(jFuncionario);

        jMenu1.setText("Fatura");

        jFaturaItemEmitir.setText("Emitir");
        jMenu1.add(jFaturaItemEmitir);

        jFaturaItemBaixaFatura.setText("Baixa Fatura");
        jMenu1.add(jFaturaItemBaixaFatura);

        jMenuBar1.add(jMenu1);

        jTreinos.setText("Treinos");

        jTreinosItemCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquivo.jpg"))); // NOI18N
        jTreinosItemCadastrar.setText("Cadastrar");
        jTreinos.add(jTreinosItemCadastrar);

        jMenuItem6.setText("Buscar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jTreinos.add(jMenuItem6);

        jMenuBar1.add(jTreinos);

        jExercicios.setText("Exercicios");

        jExercicioItemCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquivo.jpg"))); // NOI18N
        jExercicioItemCadastrar.setText("Cadastrar");
        jExercicios.add(jExercicioItemCadastrar);

        jMenuBar1.add(jExercicios);

        jMenu4.setText("Avaliação Fisica");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquivo.jpg"))); // NOI18N
        jMenuItem5.setText("Cadastrar");
        jMenu4.add(jMenuItem5);

        jMenuItem7.setText("Emitir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jGerenciarNivelAcesso.setText("Gerenciar Usuários");

        jMenuItem3.setText("NivelAcesso");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jGerenciarNivelAcesso.add(jMenuItem3);

        jMenuBar1.add(jGerenciarNivelAcesso);

        jConfigBD.setText("Configuração");

        jMenuItem1.setText("Banco de dados");
        jConfigBD.add(jMenuItem1);

        jMenuBar1.add(jConfigBD);

        jMenu5.setText("Sobre");
        jMenu5.add(jSeparator1);

        jMenuItem8.setText("About");
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        Jsair.setText("Sair");

        jSairItemLogout.setText("Logout");
        Jsair.add(jSairItemLogout);

        jSairItemSairSistema.setText("Desligar");
        Jsair.add(jSairItemSairSistema);

        jMenuBar1.add(Jsair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jAlunoItemCadastrarAlterarDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlunoItemCadastrarAlterarDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlunoItemCadastrarAlterarDeletarActionPerformed

    private void jFuncionarioItemCadastrarAlterarDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFuncionarioItemCadastrarAlterarDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFuncionarioItemCadastrarAlterarDeletarActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jsair;
    private javax.swing.JMenuItem jAlunoItemCadastrarAlterarDeletar;
    private javax.swing.JMenu jCadastroAluno;
    private javax.swing.JMenu jConfigBD;
    private javax.swing.JMenuItem jExercicioItemCadastrar;
    private javax.swing.JMenu jExercicios;
    private javax.swing.JMenuItem jFaturaItemBaixaFatura;
    private javax.swing.JMenuItem jFaturaItemEmitir;
    private javax.swing.JMenu jFuncionario;
    private javax.swing.JMenuItem jFuncionarioItemCadastrarAlterarDeletar;
    private javax.swing.JMenu jGerenciarNivelAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jSairItemLogout;
    private javax.swing.JMenuItem jSairItemSairSistema;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu jTreinos;
    private javax.swing.JMenuItem jTreinosItemCadastrar;
    // End of variables declaration//GEN-END:variables
}
