/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Acesso;
import model.Connect;
import DAO.AcessoDAO;
import DAO.UsuarioDAO;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author wesle
 */
public class FrmTelaLogin extends javax.swing.JFrame {

    private String args[] = {""};
    static Connect con = new Connect();
    /**
     * Creates new form TelaLogin
     */
    public FrmTelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTLogin = new javax.swing.JTextField();
        TXTpassword = new javax.swing.JPasswordField();
        buttonEntrarLogin = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Login");

        jLabel2.setText("Senha");

        TXTLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTLoginActionPerformed(evt);
            }
        });

        buttonEntrarLogin.setText("Entrar");
        buttonEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarLoginActionPerformed(evt);
            }
        });

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonEntrarLogin)
                            .addGap(18, 18, 18)
                            .addComponent(ButtonCancelar)
                            .addGap(34, 34, 34))
                        .addComponent(TXTpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addComponent(TXTLogin, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEntrarLogin)
                    .addComponent(ButtonCancelar)))
        );

        jLabel3.setText("UNESP FITNESS");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.blue, java.awt.Color.cyan, java.awt.Color.gray));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel3)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTLoginActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void buttonEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarLoginActionPerformed

        try {

            //Verifica se o Login e a senha Estão corretas !
            boolean login = false;
            AcessoDAO acessaDAO = new AcessoDAO();
            Acesso acesso = new Acesso();
            String usuario = TXTLogin.getText();
            String senha = String.valueOf(TXTpassword.getPassword());
            String usuarioBD = "";
            String senhaBD = "";

            ResultSet dadosAcesso = acessaDAO.buscaDadosPessoa(usuario, con);

            while (dadosAcesso.next()) {
                usuarioBD = dadosAcesso.getString("usuario");
                senhaBD = dadosAcesso.getString("senha");
            }

            login = acesso.acessarSistema(usuario, senha, usuarioBD, senhaBD);

            if (login) {

                JOptionPane.showMessageDialog(this, "Usuario: " + usuario + System.lineSeparator() + System.lineSeparator() + "Seja, Bem Vindo!!", "Bem Vindo", JOptionPane.INFORMATION_MESSAGE);

                UsuarioDAO usuarioDAO = new UsuarioDAO();
                ResultSet nivel = usuarioDAO.buscaDadosUsuario(usuarioBD, con);
                int nivelAcesso = -1;

                while (nivel.next()) {
                    nivelAcesso = nivel.getInt("nivelAcesso");
                }

                switch (nivelAcesso) {

                    case 1:
                        FrmPrincipalAdm.main(args);
                        this.dispose();
                        break;
                    case 2:
                        FrmPrincipalSecretaria.main(args);
                        this.dispose();
                        break;
                    case 3:
                        FrmPrincipalInstrutor.main(args);
                        this.dispose();
                        break;
                    case 4:
                        FrmPrincipalAluno.main(args);
                        this.dispose();
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Error!!!" + JOptionPane.ERROR_MESSAGE);
                        break;
                }

            } else {
                JOptionPane.showMessageDialog(this, "Usuario ou senha incorreta", "Erro!", JOptionPane.ERROR_MESSAGE);
            }

            this.dispose();
        } catch (Exception e) {
            System.err.println(e);;
        }
    }//GEN-LAST:event_buttonEntrarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(Connect conexao) {
        
        conexao = con ;
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonCancelar;
    private javax.swing.JTextField TXTLogin;
    private javax.swing.JPasswordField TXTpassword;
    private javax.swing.JButton buttonEntrarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
